camera:
  ros__parameters:
    base_frame_id: d435_link
    align_depth: true
    enable_pointcloud: false
    dense_pointcloud: false
    color0:
      enabled: true
      resolution: [848,480]
      fps: 60
    depth0:
      enabled: true
      resolution: [848,480]
      fps: 60
    infra1:
      enabled: false
      resolution: [848,480]
      fps: 30
    infra2:
      enabled: false
      resolution: [848,480]
      fps: 30