control_mux:
  ros__parameters:
    absolute_max_speed: 0.75 #match with data_collector_config
    ai_topic: "/ai/cmd"
    joy_topic: "/joy"
    hw_interface_topic: "/hw/cmd"
    deadzone: 0.05
    steering_trim_range: 0.3
    flip_steering: false

