data_collector:
  ros__parameters:
    absolute_max_speed: 0.75 #match with mux_config
    data_collection_rate: 5.0 #Hz
    triple_camera_mode: false #L, R, center cameras for 3x training +  edge cases
    ackermann_drive_topic: "/hw/cmd"
    center_camera_topic: "/camera/color/image_raw"
    center_camera_depth_topic: "/camera/depth/image_rect_raw"
    right_camera_topic: ""
    left_camera_topic: ""
    data_root_dir: "/home/michael/Desktop/data" #directory where data is managed (will include meta info xml)
    dataset_name: "dataset" #specific folder to put data into
    dataset_description: "This is where you can put information to describe your dataset"
    entry_notes: "If you would make a few notes about the dataset entry"

